apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: jobs
    role: single
    tier: app
  name: static-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/vm-home/"
status: {}
