apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jobs
    role: single
    tier: app
  name: static-data
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
