apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jobs
    role: single
    tier: app
  name: jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs
      role: single
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobs
        role: single
        tier: app
    spec:
      containers:
      - args:
        - bundle
        - exec
        - sidekiq
        - -c
        - "25"
        - -q
        - default
        command:
        - "/usr/src/app/development-entrypoint"
        env:
        - name: DATABASE_URL
          value: postgres://postgres:3x4mpl3@postgres:5432/example_development
        - name: RACK_ENV
          value: development
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://redis-service:6379
        - name: SIDEKIQ_CONCURRENCY
          value: "5"
        - name: SIDEKIQ_TIMEOUT
          value: "10"
        - name: LOGSTASH_HOST
          value: logstash.default.svc.cluster.local
        - name: LOGSTASH_PORT
          value: "1514"
        image: app
        imagePullPolicy: "Never"
        name: jobs
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /usr/src/app
          name: jobs-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: jobs-data
        persistentVolumeClaim:
          claimName: static-data
status: {}
