apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
    role: single
    tier: app
  name: postgres-data
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
status: {}
