apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: postgres
    role: single
    tier: app
  name: potgres-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/postgres"
status: {}
