apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis
    role: single
    tier: db
  name: redis-data
spec:
  storageClassName: fast
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
status: {}
