apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: web
      role: single
      tier: app
  endpoints:
  - port: "3000"
    path: "/metrics"
    interval: 10s
